### ISSUE TITLE
Failing CRAN status check

### ISSUE THREAD

**Issue by RasmusSkytte** [ssi-dk/diseasystore#113]
**Describe the bug**
CRAN systems have notified of failing tests on their platform:
https://cran.r-project.org/web/checks/check_results_diseasystore.html

<details><summary>Full report </summary>
<p>

<html><body>
<div class="container">
<h2>CRAN Package Check Results for Package <a href="https://cran.r-project.org/web/packages/diseasystore/index.html"> <span class="CRAN"> diseasystore </span> </a> </h2>
<p>
Last updated on 2024-01-11 10:49:20 CET.
</p>

Flavor | Version | Tinstall | Tcheck | Ttotal | Status | Flags
-- | -- | -- | -- | -- | -- | --
r-devel-linux-x86_64-debian-clang | 0.1 | 14.25 | 399.73 | 413.98 | ERROR |  
r-devel-linux-x86_64-debian-gcc | 0.1 | 13.03 | 407.74 | 420.77 | OK |  
r-devel-linux-x86_64-fedora-clang | 0.1 |   |   | 611.04 | OK |  
r-devel-linux-x86_64-fedora-gcc | 0.1 |   |   | 680.33 | OK |  
r-devel-windows-x86_64 | 0.1 | 14.00 | 459.00 | 473.00 | OK |  
r-patched-linux-x86_64 | 0.1 | 16.85 | 520.09 | 536.94 | OK |  
r-release-linux-x86_64 | 0.1 | 10.05 | 517.51 | 527.56 | OK |  
r-release-macos-arm64 | 0.1 |   |   | 226.00 | OK |  
r-release-macos-x86_64 | 0.1 |   |   | 393.00 | OK |  
r-release-windows-x86_64 | 0.1 | 17.00 | 556.00 | 573.00 | OK |  
r-oldrel-macos-arm64 | 0.1 |   |   | 201.00 | OK |  
r-oldrel-windows-x86_64 | 0.1 | 17.00 | 570.00 | 587.00 | OK |  

<h3>Check Details</h3>

<p>
Version: 0.1
<br>
Check: tests
<br>
Result: ERROR
<span style="font-family: monospace; white-space: pre;">
    Running ‘spelling.R’ [0s/1s]
    Running ‘testthat.R’ [277s/434s]
  Running the tests in ‘tests/testthat.R’ failed.
  Complete output:
    &gt; # This file is part of the standard setup for testthat.
    &gt; # It is recommended that you do not modify it.
    &gt; #
    &gt; # Where should you do additional test configuration?
    &gt; # Learn more about the roles of various files in:
    &gt; # * https://r-pkgs.org/tests.html
    &gt; # * https://testthat.r-lib.org/reference/test_package.html#special-files
    &gt; 
    &gt; library(testthat)
    &gt; 
    &gt; test_check("diseasystore")
    Loading required package: diseasystore
    #####
    
    Following drivers will be tested:
      SQLite
    
    #####
    [ FAIL 1 | WARN 0 | SKIP 0 | PASS 379 ]
    
    ══ Failed tests ════════════════════════════════════════════════════════════════
    ── Error ('test-DiseasystoreGoogleCovid19.R:251:11'): DiseasystoreGoogleCovid19 can key_join features ──
    &lt;purrr_error_indexed/rlang_error/error/condition&gt;
    Error in `pmap(.l, .f, ..., .progress = .progress)`: i In index: 1.
    Caused by error:
    ! e$message (`actual`) not identical to paste("(At least one) stratification feature does not match observable aggregator. Not implemented yet.") (`expected`).
    
    actual vs expected
    - "Check on 'w$message' failed: Must comply to pattern 'Observable already stratified by'"
    + "(At least one) stratification feature does not match observable aggregator. Not implemented yet."
    
    [ FAIL 1 | WARN 0 | SKIP 0 | PASS 379 ]
    Error: Test failures
    In addition: Warning message:
    Closing open result set, pending rows 
    Execution halted
</span>
Flavor: <a href="https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-debian-clang/diseasystore-00check.html"><span class="CRAN">r-devel-linux-x86_64-debian-clang</span></a>
</p>

</div>
</body>
</html>CRAN Package Check Results for Package diseasystore

Last updated on 2024-01-11 10:49:20 CET.
Flavor 	Version 	Tinstall 	Tcheck 	Ttotal 	Status 	Flags
r-devel-linux-x86_64-debian-clang 	0.1 	14.25 	399.73 	413.98 	ERROR 	
r-devel-linux-x86_64-debian-gcc 	0.1 	13.03 	407.74 	420.77 	OK 	
r-devel-linux-x86_64-fedora-clang 	0.1 			611.04 	OK 	
r-devel-linux-x86_64-fedora-gcc 	0.1 			680.33 	OK 	
r-devel-windows-x86_64 	0.1 	14.00 	459.00 	473.00 	OK 	
r-patched-linux-x86_64 	0.1 	16.85 	520.09 	536.94 	OK 	
r-release-linux-x86_64 	0.1 	10.05 	517.51 	527.56 	OK 	
r-release-macos-arm64 	0.1 			226.00 	OK 	
r-release-macos-x86_64 	0.1 			393.00 	OK 	
r-release-windows-x86_64 	0.1 	17.00 	556.00 	573.00 	OK 	
r-oldrel-macos-arm64 	0.1 			201.00 	OK 	
r-oldrel-windows-x86_64 	0.1 	17.00 	570.00 	587.00 	OK 	
Check Details

Version: 0.1
Check: tests
Result: ERROR
    Running ‘spelling.R’ [0s/1s]
    Running ‘testthat.R’ [277s/434s]
  Running the tests in ‘tests/testthat.R’ failed.
  Complete output:
    > # This file is part of the standard setup for testthat.
    > # It is recommended that you do not modify it.
    > #
    > # Where should you do additional test configuration?
    > # Learn more about the roles of various files in:
    > # * https://r-pkgs.org/tests.html
    > # * https://testthat.r-lib.org/reference/test_package.html#special-files
    > 
    > library(testthat)
    > 
    > test_check("diseasystore")
    Loading required package: diseasystore
    #####
    
    Following drivers will be tested:
      SQLite
    
    #####
    [ FAIL 1 | WARN 0 | SKIP 0 | PASS 379 ]
    
    ══ Failed tests ════════════════════════════════════════════════════════════════
    ── Error ('test-DiseasystoreGoogleCovid19.R:251:11'): DiseasystoreGoogleCovid19 can key_join features ──
    <purrr_error_indexed/rlang_error/error/condition>
    Error in `pmap(.l, .f, ..., .progress = .progress)`: i In index: 1.
    Caused by error:
    ! e$message (`actual`) not identical to paste("(At least one) stratification feature does not match observable aggregator. Not implemented yet.") (`expected`).
    
    actual vs expected
    - "Check on 'w$message' failed: Must comply to pattern 'Observable already stratified by'"
    + "(At least one) stratification feature does not match observable aggregator. Not implemented yet."
    
    [ FAIL 1 | WARN 0 | SKIP 0 | PASS 379 ]
    Error: Test failures
    In addition: Warning message:
    Closing open result set, pending rows 
    Execution halted
Flavor: [r-devel-linux-x86_64-debian-clang](https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-debian-clang/diseasystore-00check.html)

</p>
</details> 

In addition, CRAN sent an email with the following:

> It seems we need to remind you of the CRAN policy:
> 'Packages which use Internet resources should fail gracefully with an informative message
> if the resource is not available or has changed (and not give a check warning nor error).'
> This needs correction whether or not the resource recovers.

**To Reproduce**
Not able to reliably reproduce.

Collecting failed GitHub runs here:

> Inactive result set
https://github.com/ssi-dk/diseasystore/actions/runs/7568102823/job/20608869936?pr=117

> Expired, result set already closed
https://github.com/ssi-dk/diseasystore/actions/runs/7568102823/job/20608615875?pr=117

> Invalid result set
https://github.com/ssi-dk/diseasystore/actions/runs/7567653979/job/20607265681?pr=117

> Closing open result set, cancelling previous query 
https://github.com/ssi-dk/diseasystore/actions/runs/7567653979/job/20607266190?pr=117

> Inactive result set
https://github.com/ssi-dk/diseasystore/actions/runs/7555701810/job/20571246259?pr=117

> Closing open result set, pending rows 
https://github.com/ssi-dk/diseasystore/actions/runs/7555701810/job/20571245319?pr=117

> Closing open result set, pending rows
https://github.com/ssi-dk/diseasystore/actions/runs/7526399505/job/20485065960?pr=110

**Expected behaviour**
N/A

**Screenshots**
N/A

**Provide output from `sessionInfo()`**
N/A

**Additional context**
N/A

**Comment by RasmusSkytte** [comment]
An issue have been resolved surrounding failing gracefully when internet is not available: https://github.com/ssi-dk/diseasystore/issues/97

**Comment by RasmusSkytte** [comment]
So far, I have not been able to reproduce the error. 

I have changed to offending test slightly such that future failures should produce better messages for debugging.

**Comment by RasmusSkytte** [comment]
Issue is possibly related to the intermittent warning we have been getting
> Closing open result set, pending rows 

see: https://github.com/ssi-dk/diseasystore/actions/runs/7526399505/job/20485065960?pr=110

**Comment by RasmusSkytte** [comment]
Can possibly be fixed by using  `dbClearResult()`
https://www.rdocumentation.org/packages/DBI/versions/0.5-1/topics/dbClearResult

**Comment by RasmusSkytte** [comment]
More likely, this issue is due to the creation of a LOT of `dbplyr_###` tables.

**Comment by marcusmunch** [comment]
> More likely, this issue is due to the creation of a LOT of `dbplyr_###` tables.

Does this promote the issue to more of an SCDB one? In its current state, SCDB does not explicitly clear temporary (intermediate) tables, instead leaving it to the backend to clear temporary tables when the connection is closed. If this behavior potentially produces unexpected behavior downstream, this could be patched - potentially in the next patch version?

For now, if the issue is most likely caused by a large number of (potentially large) `dbplyr_###` tables, the test environment could maybe have some function to regularly call, removing `dbplyr_###` tables?

**Comment by RasmusSkytte** [comment]
Yes eventually. I am currently investigating which SCDB create the most of these tables without cleaning them up.

My stop-gap measure for `diseasystore` is to either clean-up these manually or to close the connections earlier.

**Comment by marcusmunch** [comment]
I do like the approach taken in ssi-dk/SCDB#80 of disconnecting and reconnecting for each test fixture&mdash;hopefully, a similar approach can keep the wrath of CRAN at bay!

**Comment by RasmusSkytte** [comment]
As far as I can tell from working on `rc-v0.2`, the issues is resolved with the changes made and with the update of `SCDB` to v0.4.
Keeping this issue open until `SCDB` is updated on CRAN and we can require `SCDB (>= 0.4.0)`
